Display list of participating libraries
MCLD/greatreadingadventure pull request #795
Opened 2021-09-15 20:40 UTC by madison-boman

Fix #461 List of participating libraries
- Adds a link, when enables in Site Settings, to the locations div in the footer
- Disables the page from being viewed if the Site Setting isnot enabled
- Discussed with HP that Branch names won't contain info such as "CLOSED, pickup at <branch name>"

2021-09-17 01:11 UTC, iafb requested changes
- Participating branch list is misaligned in firefox
- "All Participating Branches" link alignment and styling don't apply if it's the only link in the footer
- The all branches link sends to the wrong URL from info pages
- The all branches link only shows when logged in
- The participant library link option no longer works

2021-09-22 16:44 UTC, madison-boman commented
> * Participating branch list is misaligned in firefox
> * "All Participating Branches" link alignment and styling don't apply if it's the only link in the footer
> * The all branches link sends to the wrong URL from info pages
> * The all branches link only shows when logged in
> * The participant library link option no longer works

'_Participating branch list is misaligned in firefox_' and '_"All Participating Branches" link alignment and styling don't apply if it's the only link in the footer_' resolved in commit 2a1a156128c13a9bad5bf8c0e2655f6c16b541eb

'_Fix URL to work from Info pages_' resolved in commit 2fc90ca2397e84ff5838fadb1bb347c33f02a0a4

2021-09-28 16:49 UTC, iafb approved these changes

2021-09-29 21:08 UTC, k7hpn approved these changes

2021-09-29 21:23 UTC, merged